services:
  web:
    image: ghcr.io/tott0g/klassens-web:latest
    pull_policy: always
    container_name: klassens-web
    restart: always
    environment:
      - PORT=3000
      - CONVEX_URL=http://placeholder_convex_url
