services:
  web:
    build:
      context: .
      target: runner
    container_name: klassens-web
    restart: always
    environment:
      - PORT=3000
      - CONVEX_URL=http://placeholder_convex_url
      - CONVEX_SELF_HOSTED_URL=http://placeholder_convex_url
      - CONVEX_SELF_HOSTED_ADMIN_KEY=placeholder_admin_key
      # Preview overrides (for Dokploy preview deployments)
      - DOKPLOY_DEPLOY_URL=placeholder_dokploy_deploy_url
      - CONVEX_URL_PREVIEW=http://placeholder_convex_preview_url
      - CONVEX_SELF_HOSTED_URL_PREVIEW=http://placeholder_convex_preview_url
      - CONVEX_SELF_HOSTED_ADMIN_KEY_PREVIEW=placeholder_preview_admin_key
