services:
  web:
    build:
      context: .
      target: runner
    container_name: klassens-web
    restart: always
    environment:
      - PORT=3000
      - CONVEX_URL=${CONVEX_URL}
      - CONVEX_SELF_HOSTED_URL=${CONVEX_SELF_HOSTED_URL}
      - CONVEX_SELF_HOSTED_ADMIN_KEY=${CONVEX_SELF_HOSTED_ADMIN_KEY}
      - DOKPLOY_DEPLOY_URL=${DOKPLOY_DEPLOY_URL}
      - CONVEX_URL_PREVIEW=${CONVEX_URL_PREVIEW}
      - CONVEX_SELF_HOSTED_URL_PREVIEW=${CONVEX_SELF_HOSTED_URL_PREVIEW}
      - CONVEX_SELF_HOSTED_ADMIN_KEY_PREVIEW=${CONVEX_SELF_HOSTED_ADMIN_KEY_PREVIEW}
